### ISSUE TITLE
OSD on skip

### ISSUE THREAD

**Issue by sabre6** [jurialmunkey/skin.aura#26]
For OSD when playing back a video, would it be possible to have <current clock time | end clock time> show each time skip or enter is pushed (rather than episode title) -- just below the progress bar similar to when info is pressed (but not with all the show/codec info).

**Comment by jurialmunkey** [comment]
I've covered this matter before in the forums. I think it makes more sense the way it is and I don't want to add an option because the skin settings are already far too bloated.

You do this yourself by editing Includes_Statusbar.xml

Change the line 131:
`<label>$INFO[VideoPlayer.TvShowTitle,[COLOR=main_fg_70],[/COLOR][COLOR=main_fg_30]  •  [/COLOR]]$INFO[MusicPlayer.Artist,[COLOR=main_fg_70],[/COLOR][COLOR=main_fg_30]  •  [/COLOR]]$INFO[VideoPlayer.Season,,x]$INFO[VideoPlayer.Episode,,. ]$INFO[Player.Title]</label>`

To this:
`<label>$VAR[Label_OSD_FinishTime]</label>`

**Comment by sabre6** [comment]
thank you

**Comment by sabre6** [comment]
This is great. Thanks
